kennyouchou:
  system:
    # active: "test"
    # file-path: "C:/Users/kennyouchou/Desktop/upload"
    # logo-path: "C:/Users/kennyouchou/Desktop/upload/logo/logo.png"
    # file-path: "images"
    # logo-path: "/images/STATIC/logo/logo.png"
    file-path: "C:/Users/kennyouchou/Desktop/images"
    logo-path: "C:/Users/kennyouchou/Desktop/images/logo/logo.png"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/healthy_community?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource